### ISSUE TITLE
what is folder 'cc' and config.json in Cotext?

### ISSUE THREAD

**Issue by yqtian-se** [ZZR0/ISSTA22-CodeStudy#1]
Hi,

I am trying to run the Cotext on CodeXGlue dataset. 

When I run the run.sh, I got an error liks this:

```bash
    raise EnvironmentError(f"file {url_or_filename} not found")
OSError: file ./cc/config.json not found
```

May I know what is the content of "./cc" folder? Also, where I can download the cc/sentencepiece.model file? https://github.com/ZZR0/ISSTA22-CodeStudy/blob/9765bc7b96f8828ed3873545ada418371ad5e1d7/Task/Defect-Detection/cotext/run.sh#L17

Thanks a lot.

**Comment by ZZR0** [comment]
Thanks for your question. Due to the Github limited, I did not upload the file that larger than 100MB in the initial commit. And I will divide these files and upload them to github later. For this issue, I have upload the `cc` folder at `https://github.com/ZZR0/ISSTA22-CodeStudy/tree/master/CoTexT/cc`, you can change the model_path to this folder.

**Comment by yqtian-se** [comment]
Thanks a lot.
